* Testing PION for photoevaporating globules


** Summary of initial globule and globule/wind tests

*** globule-002
- Cylindrical symmetry
- This has a small neutral globule (density = 1e6 pcc), located halfway along the symmetry axis (0.5 pc) from an ionizing star in the bottom left corner
- Star is designed to mimic WR124 with a relatively soft ionizing spectrum (Teff = 33,000 K, L = 3.3e5 Lsun)
- Ambient density is 1 pcc

** Options for output formats
- By default, PION uses the silo format, but there is also the option of using FITS files, so we will try that since I am more familiar with them
- We set the parameter
 #+begin_example
   # Output File Type = {text,fits,ftab,both,...}
   OutputFileType both
 #+end_example
 and will see what happens.
- Turns out I couldn't get the FITS output to work, so I will stick with silo for now
  - It writes out a separate FITS file fo each processor it seems
 
** Pure photoionization tests
- we are basing this on the cosmological test case, but changing the parameters to be more suitable for the WR nebula knots
- The distance from the star is about 0.5 pc, which is about 20 arcsec
- The globule size is about 0.2 arcsec, which is about 0.005 pc
  - Although this is the present day size, the globule was probably larger in the past
- The shell density is about 1000 and the i-front density is about 1e4, with the neutral density being about 1e6
  - Although the original density may have been much lower, probably about 1e4
- So this is extremely similar to our parameters in the 2009 magnetic globules paper
- In that case, the evolutionary time was quite long: 100,000 years, which is a bit long for the WR nebula case
  - We should maybe make the original globules smaller, especially since we need to make them quite closely packed, so there is no room for them to have been very big to start with


*** Issues with the photoionization test
- I am having trouble getting sensible results, and I think it has to do with the non-ionizing radiation
- I am getting a heating front in the neutral gas, which causes the globule to expand
- This is using ~chem_code MPv6~, which was a bad idea since it is H only!
- So now I am going to retry with MPv5, which supposedly is based on my 2009 paper
- No, first I will try  MPv7, which is a simple two-temperature interpolation as a function of ionization fraction
- This has now worked well, so I can save this and try and move on to different parameters, and maybe add the wind

** Summary of first successful globule test
- This is now moved to [[file:test-runs/globule-001/test-single-globule-2d.txt]]
- It is in 2D cylindrical symmetry, given what I give for the boundary conditions
  #+begin_src conf
    BC_XN one-way-outflow
    BC_XP one-way-outflow
    BC_YN axisymmetric
    BC_YP one-way-outflow
  #+end_src
  - I think that if I had not specified axisymmetric it would have been in slab symmetry, but I need to check that
- The globule is big and very dense
  #+begin_src conf
    PE_SC0_overdensity 10000
    PE_SC0_xpos 1.0
    PE_SC0_ypos 0.0
    PE_SC0_zpos 0.0
    PE_SC0_vx  0.0
    PE_SC0_vy  0.0
    PE_SC0_vz  0.0
    PE_SC0_radius 0.5
    ...
    PERC_ambRO 1.67e-22 # 100 per c.c.
    PERC_ambPG 1.67e-12 # P_g = rho*kT/mu/m_p
    ...
  #+end_src
  - Strangely, the radius and position seem to be in units of the y dimension of the box, but I am not sure if that is always the case
  - The globule is like a brick. It's pressure is so high that the photoevaporation flow does not manage to drive a shock into it
    - In the side and back directions, it is overpressured with respect to the photoevaporation flow, so it expands and a rarefaction wave moves into the globule
    - This forms an expanding neutral shocked shell
- The star is something I still don't quite understand
  #+begin_src conf
    RT_strength_0    3.82e38 # erg/s for multifrequency source => 1e4 solar luminosities
    RT_Rstar____0    3   # Radius of star in solar radii.
    RT_Tstar____0    5.0e4     # Stellar effective temperature.
  #+end_src
  - So on the face of it, it is low luminosity (1e4 Lsun), but I think that gets over-ridden by the radius and Teff using Stefan-Boltzmann
  - Even so, it would be a low luminosity
  - [ ] I need to work out how to extract the ionized density so I can integrate the emission measure along the symmetry axis and work out what it thinks the ionizing flux is
- We seem to get shadowing instabilities on the front flanks, which form elephant trunk like features, but these are not well resolved

** Second globule test: globule-002
- For this one, we will try and get it the right size for the WR knots
- Still put it at 0.5 pc, but make it smaller:
  - 1e16 cm = 0.003 pc should be the final radius
  - So put at 1% of the grid size, which means we will need to use nested grids
    - So radius is 0.005 pc
    - Argh, we have a problem. Jonathan says:
      : For radiation transport, PION only works with the nested grid for a
      : point source located on the finest grid level.  I haven't yet
      : implemented rays propagating from coarse to fine levels because I'd
      : need a different time-stepping routine.  For uniform grid it works for
      : sources located anywhere (including at infinity along one of the
      : coordinate axes).
  - Keep the same density, 1e6, so that the column density will be 1.5e22
